[package]
name = "attendpi"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.7.2"
thiserror = "2.0.12"
rppal = "0.22.1"
ssd1306 = "0.10.0"
linux-embedded-hal = "0.4.0"
embedded-graphics = "0.8.1"